[package]
name = "kubectx-edit"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
ratatui = "0.20.0"
crossterm = "0.25"
tempfile = "3.2"