[package]
name = "kubectx-edit"
version = "0.0.5"
edition = "2024"
readme = "README.md"
rust-version = "1.95.0"
homepage = "https://github.com/stenstromen/kubectx-edit"
repository = "https://github.com/stenstromen/kubectx-edit"
description = "Small software utility to efficiently manage multiple kubeconfig contexts"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
ratatui = "0.30.0"
crossterm = "0.29.0"
tempfile = "3.27.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
